# Generated by Django 5.1.7 on 2025-03-12 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horas_semanales', models.IntegerField()),
                ('carga_horaria_total', models.IntegerField()),
                ('creditos', models.IntegerField()),
                ('regimen_cursado', models.CharField(max_length=20)),
                ('cuatrimestre', models.CharField(max_length=10)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Prerrequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_principal', to='universidad.materia')),
                ('prerrequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia_prerrequisito', to='universidad.materia')),
            ],
        ),
    ]
